export const countryMappings = {
    // North America
    "US": "United States",
    "CA": "Canada",
    "MX": "Mexico",

    // South America
    "BR": "Brazil",
    "AR": "Argentina",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "GY": "Guyana",
    "SR": "Suriname",

    // Europe
    "GB": "United Kingdom",
    "FR": "France",
    "DE": "Germany",
    "IT": "Italy",
    "ES": "Spain",
    "UA": "Ukraine",
    "PL": "Poland",
    "RO": "Romania",
    "NL": "Netherlands",
    "BE": "Belgium",
    "GR": "Greece",
    "CZ": "Czech Republic",
    "PT": "Portugal",
    "SE": "Sweden",
    "HU": "Hungary",
    "BY": "Belarus",
    "AT": "Austria",
    "CH": "Switzerland",
    "BG": "Bulgaria",
    "DK": "Denmark",
    "FI": "Finland",
    "SK": "Slovakia",
    "NO": "Norway",
    "IE": "Ireland",
    "HR": "Croatia",
    "MD": "Moldova",
    "BA": "Bosnia and Herzegovina",
    "AL": "Albania",
    "LT": "Lithuania",
    "MK": "North Macedonia",
    "SI": "Slovenia",
    "LV": "Latvia",
    "EE": "Estonia",
    "ME": "Montenegro",
    "LU": "Luxembourg",
    "MT": "Malta",
    "IS": "Iceland",

    // Asia
    "CN": "China",
    "IN": "India",
    "ID": "Indonesia",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "JP": "Japan",
    "PH": "Philippines",
    "VN": "Vietnam",
    "TR": "Turkey",
    "IR": "Iran",
    "TH": "Thailand",
    "MM": "Myanmar",
    "KR": "South Korea",
    "IQ": "Iraq",
    "AF": "Afghanistan",
    "SA": "Saudi Arabia",
    "UZ": "Uzbekistan",
    "MY": "Malaysia",
    "YE": "Yemen",
    "NP": "Nepal",
    "KP": "North Korea",
    "LK": "Sri Lanka",
    "SY": "Syria",
    "KZ": "Kazakhstan",
    "KH": "Cambodia",
    "JO": "Jordan",
    "AE": "United Arab Emirates",
    "LA": "Laos",
    "LB": "Lebanon",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "CY": "Cyprus",
    "PS": "Palestine",
    "BN": "Brunei",
    "MN": "Mongolia",
    "BH": "Bahrain",
    "TL": "Timor-Leste",

    // Africa
    "NG": "Nigeria",
    "ET": "Ethiopia",
    "EG": "Egypt",
    "CD": "Democratic Republic of the Congo",
    "ZA": "South Africa",
    "TZ": "Tanzania",
    "KE": "Kenya",
    "UG": "Uganda",
    "DZ": "Algeria",
    "SD": "Sudan",
    "MA": "Morocco",
    "AO": "Angola",
    "GH": "Ghana",
    "MZ": "Mozambique",
    "CI": "Côte d'Ivoire",
    "MG": "Madagascar",
    "CM": "Cameroon",
    "ZM": "Zambia",
    "ML": "Mali",
    "BF": "Burkina Faso",
    "NE": "Niger",
    "MW": "Malawi",
    "SO": "Somalia",
    "TD": "Chad",
    "ZW": "Zimbabwe",
    "GN": "Guinea",
    "RW": "Rwanda",
    "BJ": "Benin",
    "BI": "Burundi",
    "TN": "Tunisia",
    "SS": "South Sudan",
    "TG": "Togo",
    "SL": "Sierra Leone",
    "LY": "Libya",
    "CG": "Republic of Congo",
    "LR": "Liberia",
    "MR": "Mauritania",
    "ER": "Eritrea",
    "GM": "Gambia",
    "BW": "Botswana",
    "GA": "Gabon",
    "LS": "Lesotho",
    "GW": "Guinea-Bissau",
    "DJ": "Djibouti",
    "SZ": "Eswatini",

    // Oceania
    "AU": "Australia",
    "PG": "Papua New Guinea",
    "NZ": "New Zealand",
    "FJ": "Fiji",
    "SB": "Solomon Islands",
    "VU": "Vanuatu",
    "NC": "New Caledonia",
    "PF": "French Polynesia",

    // Add reverse mappings
    "United States": "United States",
    "China": "China",
    "South Korea": "South Korea",
    "The Netherlands": "Netherlands",
    "Lithuania": "Lithuania"
};

// Helper function to get country name from code or vice versa
export const getCountryName = (identifier) => {
    return countryMappings[identifier] || identifier;
};

export const getCountryCode = (name) => {
    return Object.keys(countryMappings).find(key => countryMappings[key] === name) || name;
};